### ISSUE TITLE
Public peers not accepting new quic connections

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/mycelium#331] opened 2024-07-11 00:40 UTC
I noticed in my logs that a couple of the public peers aren't accepting quic connections. But the same peers are accepting connections via tcp.

```
Couldn't complete quic connection to Quic 136.243.47.186:9651: aborted by peer: the server refused to accept a new connection
Couldn't complete quic connection to Quic 185.69.166.8:9651: aborted by peer: the server refused to accept a new connection
```

These are two of three peers that I happened to use quic with. The other one is working okay: `quic://185.69.166.7:9651`. I didn't test the rest with quic.

**Comment by LeeSmet** [comment] 2024-07-11 09:36
Duplicate of https://github.com/threefoldtech/mycelium/issues/309

**Closed by LeeSmet** 2024-07-11 09:36 UTC
