### ISSUE TITLE
Could not connect to machines created from the dashboard using mycelium on windows

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/mycelium#474] opened 2024-10-10 05:53 UTC
### Description : 

while [testing Mycelium on Windows and Myceloumflut](https://github.com/threefoldtech/myceliumflut/issues/66) 

Mycelium worked fine on Windows. I could easily ping Mycelium using `ping -6  <mycelium_ip>` and communicate with other machines having mycelium installed and the binary running : 
![telegram-cloud-photo-size-4-5778481758210212434-y](https://github.com/user-attachments/assets/234011fc-eb65-46d0-aee8-ac04adf1288a)
![telegram-cloud-photo-size-4-5778481758210212441-y](https://github.com/user-attachments/assets/84fdaa6e-23d4-43c4-9dfd-ba52a82bd5a6)

but could not do the same to machines deployed from the grid from windows
<img width="872" alt="Screenshot 2024-10-07 at 4 02 49 PM" src="https://github.com/user-attachments/assets/bdfb8531-36f8-4bab-9aa5-8bf37534fef3">

**Comment by LeeSmet** [comment] 2024-10-10 08:29
Can you try to ping the IP instead of trying to ssh to it?

**Comment by khaledyoussef24** [comment] 2024-10-13 10:38
@LeeSmet pinging ips works fine with me 
![telegram-cloud-photo-size-4-5773790133504558003-y](https://github.com/user-attachments/assets/6a82c8a9-bc14-4326-a8ce-7cd4e1724708)

**Comment by LeeSmet** [comment] 2024-10-14 08:58
Given that ping works fine, this indicates that mycelium itself seems to be functioning as expected and delivers packets. Connection timed out would suggest then that the tcp connection handshake, or later ssh connection handshake doesn't complete, i.e. packets are lost/dropped. I'd suggest to try and ssh to the machine using another transport (regular ipv6/public ipv4 if that is available/wireguard). If that works, check if there are firewall rules and what those are, if the ssh server is listening on addresses which include the mycelium interface, and  if there is nothing there, tcpdump the mycelium interface to see if any packets actually do come in for the ssh connection

**Comment by iwanbk** [comment] 2024-10-15 04:35
> Mycelium worked fine on Windows
> but could not do the same to machines deployed from the grid from windows

Hi @khaledyoussef24 
Could you try to change Windows with other OS, like Linux or macos with mycelium binary from this repo (not from `myceliumflut` repo)

**Comment by khaledyoussef24** [comment] 2024-10-21 14:25
Working fine on both linux and macos 

And has the abiltiy to connect to machines with mycelium created on the grid

**Comment by iwanbk** [comment] 2024-10-22 10:59
OK, i can reproduce it, using command line mycelium, not the flutter one.

Did few scenarios
1. windows to Linux(my PC)
- ping OK
- ssh OK

2.Linux (my PC) to Linux on grid
- ping OK
- SSH OK

3. Windows to Linux on grid
- ping OK
- ssh : failed
```console
ssh: connect to host 4d3:395f:77d0:e398:ff0f:0:400:2 port 22: Connection timed out
```

**Comment by iwanbk** [comment] 2024-10-23 04:21
I got the error log
```console
thread 'tokio-runtime-worker' panicked at C:\Users\Administrator\mycelium\mycelium\src\tun\windows.rs:64:40:
range end index 1452 out of range for slice of length 1400
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
```
And found that max packet size and MTU are 1400 instead of 1500.
Sent the fix on #484

**Comment by khaledyoussef24** [comment] 2024-10-23 09:44
myceliumflut latest version made by Iwan worked fine and while running the app ,I could connect to machines on the grid using mycelium ip
![telegram-cloud-photo-size-4-5819062692281960362-y](https://github.com/user-attachments/assets/832a5270-ead5-40a3-a02f-de1f5417d58c)

**Comment by khaledyoussef24** [comment] 2024-10-23 09:45
It was using myceliumflut.  shall we consider this as done ?

**Comment by iwanbk** [comment] 2024-10-23 11:15
> shall we consider this as done ?

It will be done after #484 getting merged.

The binary i sent to you is a PoC of this solution.

**Closed** 2024-10-25 11:34 UTC
